services:
  db:
    image: postgres:16
    environment:
      POSTGRES_USER: bankuser
      POSTGRES_PASSWORD: bankpass
      POSTGRES_DB: bankdb
    ports: ["5432:5432"]
    volumes: [dbdata:/var/lib/postgresql/data]

  backend:
    build: ./backend
    environment:
      DATABASE_URL: postgres://bankuser:bankpass@db:5432/bankdb
    ports: ["4000:4000"]
    depends_on: [db]

  frontend:
    build: ./frontend
    ports: ["3000:5173"]
    depends_on: [backend]

volumes:
  dbdata:
